- name: Setup for storing the bacula catalog
  block:

    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Proceed to setup for the bacula catalog if mysql is running
      block:

        - name: Create a database for bacula to use
          community.mysql.mysql_db:
            login_unix_socket: /var/run/mysqld/mysqld.sock
            name: bacula
            state: present

        - name: Create a user for bacula to use
          community.mysql.mysql_user:
            host: "{{ backup_director_host }}"
            login_unix_socket: /var/run/mysqld/mysqld.sock
            name: "{{ backup_database_username }}"
            password: "{{ backup_database_password }}"
            priv: 'bacula.*:ALL'
            state: present
            # BUG: On subsequent executions of this task an exception occurs:
            # https://github.com/ansible/ansible/issues/51356
            # We are using ignore_errors as a workaround for this issue.
          ignore_errors: yes

      when:
        - ansible_facts['services']['mysql']['state'] == 'running'

  become: yes
